DROP TABLE Person CASCADE;
DROP TABLE Employee CASCADE;
DROP TABLE Customer CASCADE;
DROP TABLE BookingRoom CASCADE;
DROP TABLE Room CASCADE;
DROP TABLE BookingRestaurant CASCADE;
DROP TABLE FoodDish CASCADE;